/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_worldclass_activities_MainActivity.h"
#include <GLES2/gl2.h>
/* Header for class com_worldclass_activities_MainActivity */

JNIEXPORT jstring JNICALL Java_com_worldclass_activities_MainActivity_getStringFromNative
  (JNIEnv * env, jobject obj)
  {
    return (*env)->NewStringUTF(env, "Hello from JNI !");
  }

  void Java_com_worldclass_utils_MyGLRenderer_JNIOnSurfaceCreated(JNIEnv* env, void* reserved)
  {
      GLubyte* puiOpenGLVersion = glGetString(GL_VERSION);
      LOGD("OpenGL Version: \"%s\"\n", (const char*)puiOpenGLVersion);
  }

  void Java_com_worldclass_utils_MyGLRenderer_JNIOnSurfaceChanged(JNIEnv* env, void* reserved, int w, int h)
  {
      LOGD("JNIOnSurfaceChanged %dx%d\n", w, h);
      glViewport(0, 0, w, h);
  }

  void Java_com_worldclass_utils_MyGLRenderer_JNIOnDrawFrame(JNIEnv* env, void* reserved)
  {
      // Clear the screen to a random shade of grey
      float fColor = (float)(rand() % 256) / 255.0f;
      glClearColor(fColor, fColor, fColor, 1.0f);
      glClear(GL_COLOR_BUFFER_BIT);
  }