/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_worldclass_activities_MainActivity.h"
/* Header for class com_worldclass_activities_MainActivity */

JNIEXPORT jstring JNICALL Java_com_worldclass_activities_MainActivity_getStringFromNative
  (JNIEnv * env, jobject obj)
  {
    return (*env)->NewStringUTF(env, "Hello from JNI !");
  }